name: Autonomous Content Engine
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai python-frontmatter GitPython
      - name: Run Autonomos Engine
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AFFILIATE_LINKS: ${{ secrets.AFFILIATE_LINKS }}
        run: python autonomos.py


